export default [
  {
    icon: 'star',
    id: 1,
    level: 1,
    name: '基础组件',
    open: false,
    page: '',
    children: [
      {
        icon: '',
        id: 2,
        level: 2,
        name: '基础布局',
        open: false,
        page: '/pages/components/layout',
      },
      {
        icon: '',
        id: 3,
        level: 2,
        name: '按钮',
        open: false,
        page: '/pages/components/button',
      },
      {
        icon: '',
        id: 4,
        level: 2,
        name: '加载框',
        open: false,
        page: '/pages/components/loading',
      },
      {
        icon: '',
        id: 5,
        level: 2,
        name: '加载图标',
        open: false,
        page: '/pages/components/loader',
      },
      {
        icon: '',
        id: 6,
        level: 2,
        name: '表格',
        open: false,
        page: '/pages/components/table',
      },
      {
        icon: '',
        id: 7,
        level: 2,
        name: '提示',
        open: false,
        page: '/pages/components/toast',
      },
      {
        icon: '',
        id: 8,
        level: 2,
        name: '网页视图',
        open: false,
        page: '/pages/components/webview',
      },
      {
        icon: '',
        id: 9,
        level: 2,
        name: '应用更新',
        open: false,
        page: '/pages/components/updater',
      },
    ]
  },
  {
    icon: 'level',
    id: 20,
    level: 1,
    name: '表单校验',
    open: false,
    page: '',
    children: [
      {
        icon: '',
        id: 21,
        level: 2,
        name: '表单校验',
        open: false,
        page: '/pages/js/checker',
      },
    ]
  },
  {
    icon: 'chat',
    id: 30,
    level: 1,
    name: '工具类',
    open: false,
    page: '',
    children: [
      // {
      //   icon: '',
      //   id: 31,
      //   level: 2,
      //   name: '蓝牙',
      //   open: false,
      //   page: '/pages/js/bluetooth',
      // },
      {
        icon: '',
        id: 32,
        level: 2,
        name: '网路请求',
        open: false,
        page: '/pages/js/http',
      },
      {
        icon: '',
        id: 33,
        level: 2,
        name: '全局混入',
        open: false,
        page: '/pages/js/mixin',
      },
      {
        icon: '',
        id: 34,
        level: 2,
        name: '优化类',
        open: false,
        page: '/pages/js/optimize',
      },
      {
        icon: '',
        id: 35,
        level: 2,
        name: '分页',
        open: false,
        page: '/pages/js/pager',
      },
      {
        icon: '',
        id: 36,
        level: 2,
        name: '状态管理',
        open: false,
        page: '/pages/js/store',
      },
      {
        icon: '',
        id: 37,
        level: 2,
        name: '提示类',
        open: false,
        page: '/pages/js/tips',
      },
    ]
  }
]
