export default [
  {
    icon: 'gift',
    id: 1,
    level: 1,
    name: '基础组件',
    open: false,
    page: '',
    children: [
      {
        icon: 'gift',
        id: 2,
        level: 2,
        name: '基础布局',
        open: false,
        page: '/pages/components/layout',
      },
      {
        icon: 'tags',
        id: 3,
        level: 2,
        name: '按钮',
        open: false,
        page: '/pages/components/button',
      },
      {
        icon: 'grid-fill',
        id: 4,
        level: 2,
        name: '图标',
        open: false,
        page: '/pages/components/icons',
      },
      {
        icon: 'clock',
        id: 4,
        level: 2,
        name: '加载框',
        open: false,
        page: '/pages/components/loading',
      },
      {
        icon: 'reload',
        id: 5,
        level: 2,
        name: '加载图标',
        open: false,
        page: '/pages/components/loader',
      },
      {
        icon: 'list',
        id: 6,
        level: 2,
        name: '表格',
        open: false,
        page: '/pages/components/table',
      },
      {
        icon: 'question-circle',
        id: 7,
        level: 2,
        name: '提示',
        open: false,
        page: '/pages/components/toast',
      },
      {
        icon: 'ie',
        id: 8,
        level: 2,
        name: '网页视图',
        open: false,
        page: '/pages/components/webview',
      },
      {
        icon: 'bag',
        id: 9,
        level: 2,
        name: '应用更新',
        open: false,
        page: '/pages/components/updater',
      },
      {
        icon: 'zhuanfa',
        id: 10,
        level: 2,
        name: '服务器切换',
        open: false,
        page: '/pages/components/apis',
      },
    ]
  },
  {
    icon: 'order',
    id: 20,
    level: 1,
    name: '表单校验',
    open: false,
    page: '',
    children: [
      {
        icon: 'order',
        id: 21,
        level: 2,
        name: '表单校验',
        open: false,
        page: '/pages/js/checker',
      },
    ]
  },
  {
    icon: 'thumb-up',
    id: 30,
    level: 1,
    name: '工具类',
    open: false,
    page: '',
    children: [
      // {
      //   icon: '',
      //   id: 31,
      //   level: 2,
      //   name: '蓝牙',
      //   open: false,
      //   page: '/pages/js/bluetooth',
      // },
      {
        icon: 'chrome-circle-fill',
        id: 32,
        level: 2,
        name: '网路请求',
        open: false,
        page: '/pages/js/http',
      },
      {
        icon: 'integral',
        id: 34,
        level: 2,
        name: '优化类',
        open: false,
        page: '/pages/js/optimize',
      },
      {
        icon: 'list-dot',
        id: 35,
        level: 2,
        name: '分页',
        open: false,
        page: '/pages/js/pager',
      },
      {
        icon: 'pushpin',
        id: 36,
        level: 2,
        name: '状态管理',
        open: false,
        page: '/pages/js/store',
      },
      {
        icon: 'bell',
        id: 37,
        level: 2,
        name: '提示类',
        open: false,
        page: '/pages/js/tips',
      },
      // #ifdef APP-PLUS
      {
        icon: 'scan',
        id: 38,
        level: 2,
        name: 'mPaaS 扫码',
        open: false,
        page: '/pages/js/mpaas-scan',
      },
      // #endif
      {
        icon: 'bell',
        id: 38,
        level: 2,
        name: '蓝牙打印',
        open: false,
        page: '/pages/examples/ble',
      }
    ]
  }
]
